[package]
name = "bevy_ecs_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", features = ["dynamic_linking"]}
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
